# Generated by Django 5.2.17 on 2026-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('seller_type', models.CharField(choices=[('roaster', 'Roaster'), ('shop', 'Shop'), ('importer', 'Importer')], default='roaster', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('site_url', models.URLField(blank=True, default='')),
                ('instagram', models.CharField(blank=True, default='', max_length=200)),
                ('relationship', models.CharField(choices=[('indexed', 'Indexed'), ('partner', 'Partner')], default='indexed', max_length=20)),
            ],
        ),
    ]
