# Generated by Django 5.2.17 on 2026-09-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeanListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, choices=[('Washed', 'Washed'), ('Natural', 'Natural'), ('Honey', 'Honey'), ('Anaerobic', 'Anaerobic'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('roast_level', models.CharField(blank=True, choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Dark', 'Dark'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('format', models.CharField(blank=True, choices=[('Whole bean', 'Whole bean'), ('Ground', 'Ground'), ('Capsule', 'Capsule'), ('Pods', 'Pods'), ('Other', 'Other')], max_length=20, null=True)),
                ('flavor_notes', models.TextField(blank=True, null=True)),
                ('roasted_on', models.DateField(blank=True, null=True)),
                ('weight_g', models.FloatField(blank=True, null=True)),
                ('price_toman', models.BigIntegerField(blank=True, null=True)),
                ('price_per_100g', models.FloatField(blank=True, null=True)),
                ('specialty_score', models.FloatField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, default='')),
                ('source_key', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='catalog.seller')),
            ],
        ),
    ]
