# Generated by Django 5.2.17 on 2026-09-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_beanlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('grinder', 'Grinder'), ('brewer', 'Brewer'), ('kettle', 'Kettle'), ('filter', 'Filter'), ('accessory', 'Accessory')], max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('key_specs', models.TextField(blank=True, null=True)),
                ('price_toman', models.BigIntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, default='')),
                ('source_key', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='catalog.seller')),
            ],
        ),
    ]
