# Generated by Django 5.2.17 on 2026-09-13 18:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gearlisting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beanlisting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='bean_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='gearlisting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='gear_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
