# Generated by Django 5.2.17 on 2026-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_beanlisting_bean_name_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beanlisting',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='beanlisting',
            name='source_key',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='gearlisting',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gearlisting',
            name='source_key',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
