# Generated by Django 5.2.17 on 2026-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beanlisting',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='gearlisting',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
